### ISSUE TITLE
Master and thanks

### ISSUE THREAD

**Issue by IdiotCat** [ToadsworthLP/Millenium#1]
Hello I wrhite here 'cause I tried millenium and the master version don't work: it give me a few error (I'm on version 2017.1.1f1) but the node editor version work fine.

and also to thanks you making that I was realy wanted to know how to make a paper mario fan game

**Comment by ToadsworthLP** [comment]
It's been a while since I actually tested if cloning Millenium actually works because I assumed it would, but I strongly advise you not to use version from the node editor branch since it's horribly outdated and only exists to store "my" node editor code (though most of it is taken from a tutorial on exactly that topic because I'm lazy) which I may or may not use in the future. I'll now investigate the issue and close it when a fix has been added.
Thank you for letting me know!

**Comment by ToadsworthLP** [comment]
Fixed in #af7f13b
